pipeline {

  agent { label 'agent-1' } 

  parameters{
    choice(name: 'CHOOSE', choices: ['apply', 'destroy'], description: 'Pick Apply or destroy')
  }

  stages{

    stage('INIT AND PLAN'){

      steps{

        withAWS(region: 'us-east-1', credentials: 'aws-auth'){

          sh """
            cd 01-VPC
            terraform init -upgrade
            terraform init -reconfigure
            terraform plan -out=vpc.txt
          """
        }
      }
    }

    stage('APPLY OR DESTROY'){

      steps{

        withAWS(region: 'us-east-1', credentials: 'aws-auth'){

          sh """
            cd 01-VPC
            if [ ${params.CHOOSE} == 'apply' ]
            then
              terraform apply -auto-approve vpc.txt
            elif [ ${params.CHOOSE} == 'destroy' ]
            then
              terraform destroy -auto-approve
            fi
          """
        }
      }
    }
  }

  post {

    always{
      deleteDir()
    }
    success{
      echo "PIPELINE WAS SUCCESS"
    }
    failure{
      echo "PIPELINE GETS FAILURE"
    }
  }
}