pipeline {

    agent { label 'agent-1' } 

    stages{

        stage('INIT AND PLAN'){

            steps{

                withAWS(region: 'us-east-1', credentials: 'aws-creds'){

                    sh """
                        cd 01-VPC
                        terraform init -upgrade
                        terraform init -reconfigure
                        terraform plan -out=vpc.txt

                    """
                }
            }
        }
    }
}